// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkBzhpfYj1MBjhWDbAM7jedtQcTqQ9zK4',
    appId: '1:928288804714:web:aca1420b7d3cada78c1f13',
    messagingSenderId: '928288804714',
    projectId: 'gchat-a8c78',
    authDomain: 'gchat-a8c78.firebaseapp.com',
    storageBucket: 'gchat-a8c78.appspot.com',
    measurementId: 'G-P7ZGMYPK39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs7oeoUfvSwIivau_7DpYgdPn4AcpyahA',
    appId: '1:928288804714:android:d2903f60b5c219cb8c1f13',
    messagingSenderId: '928288804714',
    projectId: 'gchat-a8c78',
    storageBucket: 'gchat-a8c78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD944McXbxByzrUMhPod6InnLK7gJea4Yo',
    appId: '1:928288804714:ios:7f470f7c31e676a68c1f13',
    messagingSenderId: '928288804714',
    projectId: 'gchat-a8c78',
    storageBucket: 'gchat-a8c78.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );
}
